### ISSUE TITLE
readme link to okd doc out of date

### ISSUE THREAD

**Issue by dlbewley** [openshift/service-ca-operator#145]
In the readme, I suspect that the broken link to OKD doc:
- https://docs.okd.io/latest/dev_guide/secrets.html#service-serving-certificate-secrets
Should now be
- https://docs.okd.io/latest/security/certificates/service-serving-certificate.html

**Comment by s-urbaniak** [comment]
/close

@dlbewley please open a bugzilla or a support case. Thank you!
