### ISSUE TITLE
Move from PKCS#1 to PKCS#8 private keys

### ISSUE THREAD

**Issue by jackevans43** [openshift/service-ca-operator#146]
Setting the `service.beta.openshift.io/serving-cert-secret-name` annotation results in a PKCS#1 private key being generated in the secret. PKCS#1 only supports RSA private keys and is no longer supported by some applications (eg. logstash) which now expect the more modern PKCS#8 format for private keys.

**Comment by s-urbaniak** [comment]
@jackevans43 please open a bugzilla or a support case. Thank you!
