### ISSUE TITLE
comparison to cert-manager

### ISSUE THREAD

**Issue by horis233** [openshift/service-ca-operator#162]
## Need Help
Could we have a document to make a comparison to the [cert-manager](https://cert-manager.io/)?

For example, If the cert-manager is onboarded to the OCP/OKD, in which situation we should choose the cert-manager and in which situation we should choose the service-ca-operator?

Also, could the service-ca-operator support the BYOK case?

**Comment by s-urbaniak** [comment]
@horis233 please open a bugzilla, support case, or contact Auth PM within RedHat directly.
/close
