### ISSUE TITLE
Make minTimeLeft configurable, service-signing-certs can and should be rotated before the one hour expiry

### ISSUE THREAD

**Issue by Br0mZ** [openshift/service-ca-operator#166]
If a cluster is not updated (which should not happen but does happen), the service-signing-certs will rotate one hour before expiry.
The chance that the involved pods will restart within that hour is really small. If you increase that window to for example a month, this chance will increase a lot.

There is a comment in the code which suggests a TODO to set the timeleft as a percentage of the lifespan of the cert.
And/Or include this setting in the service-ca-operator-config configmap, so it's configurable if needed.

https://github.com/openshift/service-ca-operator/blob/a27da0d06f877bedc1b373ff459a512f668fcd1e/pkg/controller/servingcert/controller/secret_updating_controller.go#L56-L57

**Comment by Br0mZ** [comment]
I did open a case with RedHat Support to discuss this.

Now I have a better understanding of the whole process:
The service CA operator will rotate the CA cert that issues the service signing certs.
This CA is valid for 26 months and gets rotated after 13 months.
The old one will still be available to trust the issued certs.
The controller within the CA operator will constantly loop and check if issued certs will require regeneration (for example if not issued by the latest CA) and will replace the key material.
An upgrade to the cluster will drain all the nodes and restart pods, so the new keys will be in use.

So in theory, we will never reach the situation in which the secret will reach that 1 hour mark before expiration in which it also regenerates the key material.

Conclusion: very low priority

**Comment by s-urbaniak** [comment]
@Br0mZ thank you for opening a support case. closing this one out.
