### ISSUE TITLE
Updates needed in README

### ISSUE THREAD

**Issue by candita** [openshift/service-ca-operator#244]
Someone asked me about using secret serving certs, and I was going to refer them to these links in this README, but they are broken.  Openshift docs don't give much information for developers.  Any ideas on updates?

> Many OpenShift ClusterOperators share common build, test, deployment, and update methods.
> For information about how to build, deploy, test, update, and develop OpenShift ClusterOperators, see
> [OpenShift ClusterOperator and Operand Developer Document](https://github.com/openshift/enhancements/blob/master/enhancements/dev-guide/operators.md#how-do-i-buildupdateverifyrun-unit-tests)
> 
> This section explains how to deploy OpenShift with your version of a service-ca-operator image:
> [Testing a ClusterOperator/Operand image in a cluster](https://github.com/openshift/enhancements/blob/master/enhancements/dev-guide/operators.md#how-can-i-test-changes-to-an-openshift-operatoroperandrelease-component)

**Comment by lunarwhite** [comment]
Hey @candita, I've raised a fixing PR: https://github.com/openshift/service-ca-operator/pull/241 (waiting for reviews).

Could you please take a look when you get a chance? It would be really helpful.
