### ISSUE TITLE
Statefulset headless services should contain a wildcard ALT-NAME

### ISSUE THREAD

**Issue by rgordill** [openshift/service-ca-operator#25]
According with https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-identity, an statefulset can use a headless service to identify each pod. To cover this use case when generating a cert for a headless service, other than the current subject alt-names, it will be useful to have a wildcard for the pod names. Example:

**DNS Name: &ast;.broker-amq-headless.broker.svc**
DNS Name: broker-amq-headless.broker.svc 
DNS Name: broker-amq-headless.broker.svc.cluster.local

**Comment by mrogers950** [comment]
@openshift/sig-auth Thoughts on this RFE? If we wanted to support it I would suggest a separate service annotation i.e.,  `service.beta.openshift.io/service-serving-wildcard`

**Comment by enj** [comment]
> @openshift/sig-auth Thoughts on this RFE? If we wanted to support it I would suggest a separate service annotation i.e., `service.beta.openshift.io/service-serving-wildcard`

Not in 4.0.  Also not sure if wildcard is safe (do not have enough info to say one way or another).

**Comment by rgordill** [comment]
What other alternative may cover the use case?

**Comment by aaronmcohen** [comment]
Please consider this enhancement for the next release of OCP.

**Comment by aaronmcohen** [comment]
Please consider this enhancement for the next release of OCP.

**Comment by aaronmcohen** [comment]
Please consider this enhancement for the next release of OCP.

**Comment by mtrmac** [comment]
RFC: https://github.com/openshift/enhancements/pull/674 .

A wildcard seems too broad; it makes it impossible to guarantee individual pod identities within a StatefulSet (or even to differentiate between different StatefulSets attached to a single service), and https://github.com/kubernetes/dns/blob/master/docs/specification.md only specifies what DNS records must exist, not what must not exist, so such a certificate could match unwanted DNS entries.

**Comment by mtrmac** [comment]
This was implemented in #149, for headless services only.
