### ISSUE TITLE
Add ExtendedKeyUsages clientAuth

### ISSUE THREAD

**Issue by nsieg** [openshift/service-ca-operator#62]
Certificates generated using the `service.beta.openshift.io/serving-cert-secret-name` annotation receive only `serverAuth` for x509 v3 extension ExtendedKeyUsages:
```
#3: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
]
```
When trying to use the provided certificate for a client in mutual TLS, the server will not allow the certificate:

```
Caused by: sun.security.validator.ValidatorException: Extended key usage does not permit use for TLS client authentication
```
Is it possible to add `clientAuth` to the ExtendedKeyUsages via the cryptoextensions as mutual TLS may be a common usage scenario for certificates generated using the annotation?

**Comment by mrogers950** [comment]
We would not want to just add client usages to the certs without being able to authorize that some client is allowed to have a client cert. I understand the desire for mTLS with serving certs, but the solution would be more involved than that. For now, a cluster admin can use the service-CA signing secret and issue a client cert with it using openssl.

**Comment by michaelgeorgeattard** [comment]
/reopen

Would it be possible to add an annotation to opt in for additional `ExtendedKeyUsages`?
